export enum PATH {
  ACERCADE='acercade',
  ARTICULO='articulo',
  CONTACTO='contacto',
  HOME='',
  IMAGEN='galeria',
  INICIO='inicio',
  PERSONA='personas',
  NOMBRE='nombres',
  USUARIO='usuario',
  CREAR_USUARIOS = 'crear-usuarios',
  PRODUCTOS = 'productos',
  CREAR_PRODUCTOS = 'crear-productos',
  LOGIN = 'login',
}
